### ISSUE TITLE
Crash on large file

### ISSUE THREAD

**Issue by jgm** [treeman/tree-sitter-djot#6] opened 2024-03-20 16:24 UTC
https://github.com/jgm/djoths/blob/main/benchmark/m.dj

Parsing this I get:
```
Assertion failed: (s->blocks_to_close == 0), function tree_sitter_djot_external_scanner_scan, file scanner.c, line 1340.
zsh: abort      tree-sitter parse m.dj
```
I haven't been able to reproduce this with a smaller file yet.
But this one actually crashes Emacs when I open the file using this treesitter grammar.

**Comment by treeman** [comment] 2024-03-20 19:31
Ah, I was going to remove the asserts and prefer `ERROR` instead, but I forgot.

The file should now parse without crashing, although I haven't fixed the root cause of the crash yet.

**Comment by jgm** [comment] 2024-03-20 21:29
Now I can open the file.  Highlighting is basically instant, even for such a big file, and I don't see any mistakes yet (though I haven't implemented everything yet in my Emacs mode).

**Comment by treeman** [comment] 2024-03-21 04:15
Great to hear, I'm really glad you took the time to do some performance tests as it's not something I've prioritized yet.

I did see some `ERROR` failures from the file that I'll take a look at later when I have time.

**Comment by treeman** [comment] 2024-03-23 01:05
Went through the file and (hopefully) filed the `ERROR` issues i could find, so closing this.

But feel free to file more issues as you find them.

**Closed as completed by treeman** 2024-03-23 01:05 UTC
